name: 'Build & Test'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo python3 -m pip install prospector[with_everything]
      - run: prospector --strictness high
